[1m[2m# Unformatted Error Output:[22m[22m
[2m# [22m[2mFile "tests/__tests__/refmterr/__fixtures__/type_AppliedTooMany/type_AppliedTooMany_3.ml", line 11, characters 5-30:[22m
[2m# [22m[2mError: The function applied to this argument has type[22m
[2m# [22m[2m         customLogOutputProcessors:(string -> string) list ->[22m
[2m# [22m[2m         customErrorParsers:(string * string list) list -> unit[22m
[2m# [22m[2mThis argument cannot be applied with label ~raiseExceptionDuringParse[22m


[31m[1m[7m ERROR [27m[22m[39m [36m[4mtests/__tests__/refmterr/__fixtures__/type_AppliedTooMany/type_AppliedTooMany_3.ml[24m[39m[2m[4m:11 5-30[24m[22m 

[2m 8 â”† [22m[35m[2mlet[22m[39m[2m _ =[22m
[2m 9 â”† [22m[2m  parseFromStdin[22m
[2m10 â”† [22m[2m    [22m[33m[2m~refmttypePath[22m[39m
[31m[2m11 â”† [22m[39m[2m    ~[22m[31m[1m[4mraiseExceptionDuringParse[24m[22m[39m[2m=true[22m
[2m12 â”† [22m[2m    [22m[33m[2m~customLogOutputProcessors[22m[39m[2m=[][22m
[2m13 â”† [22m[2m    [22m[33m[2m~customErrorParsers[22m[39m[2m:[][22m

The function has type (
  ~customLogOutputProcessors: list(string => string),
  ~customErrorParsers: list((string, list(string)))
) =>
unit

This function doesn't accept an argument named ~raiseExceptionDuringParse.


